name: Hybrid TrendPulse Scanner

on:
  schedule:
    - cron: '*/30 * * * *'    # every 30 minutes
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pandas numpy requests yfinance

      - name: Run Hybrid Scanner
        env:
          COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python crypto_trend_scanner.py
