name: Crypto Trend Scanner

on:
  schedule:
    # Run every hour for maximum market coverage
    - cron: '0 * * * *'
  workflow_dispatch: # Enable manual execution

jobs:
  trend-analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 hours maximum
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Configure Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install required packages
      run: |
        pip install pandas numpy requests
        
    - name: Execute market trend analysis
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
      run: python crypto_trend_scanner.py
